[App]

LogLevel = "trace"

[CL]

CLIPAddress = "127.0.0.1"
CLPort = 48010

ThisIPAddress = "127.0.0.1"
ThisPort = 50001


[Sim]

InvertElevator = true
InvertAileron = false
InvertCLElevatorTrim = false
PropWashOffset = 0x66f8
CLElevatorTrimOffset = 0x66C4
APRollEngagedOffset = 0x66C0
APPitchEngagedOffset = 0x66C1
APPitchLimitsOffset = 0x66C6

CLForceEnabledOffset = 0x66c7
CLEngageOffset = 0x66c8

[Model]

# == H/W begin ==

AileronFrictionCoeff = -3
AileronDumpingCoeff = -3

AileronPositionFollowingP = 40
AileronPositionFollowingI = 0
AileronPositionFollowingD = 40

ElevatorFrictionCoeff = -3
ElevatorDumpingCoeff = -6

ElevatorPositionFollowingP = 60
ElevatorPositionFollowingI = 0
ElevatorPositionFollowingD = 40

# == H/W end ==

# == Common begin ==
CLExponent = 2.0

HTailPosLon = 13.7
WingRootChord = 5.0

EngineVibAirGain = 0.1
CalculatePropWash = false

# == Common end ==

# == Elevator begin ==

ElevatorArea = 1.2
ElevatorNeutralPos = 0.0
ElevatorTrimGain = 1.2
ElevatorTrimNeutralPos = 0.0

ElevatorAlphaGain = -1.0
ElevatorAlphaScaleSpeedKn = 30.0
# FIXME
ElevatorPRGain = 0.0

PropWashElevatorCoeff = 1.0

ElevatorEngineFlowGain = 35.0
ElevatorEngineFreqGain = 1.0
ElevatorEngineFreqMin = 2.5

# 255 - FIXME
ElevatorVibStallGain = 255.0
ElevatorVibStalFreq = 30.0

ElevatorVibRunwayGain = 50.0
ElevatorVibRunwayFreq = 15.0

MaxElevatorLift = 2.83
MaxElevatorAngleDegrees = 17.0

# == Elevator end

# == Ailerons begin ==

AileronArea = 1.1
AileronTrimGain = 0.5
PropWashAileronCoeff = 0.0
MaxAileronLift = 2.83
MaxAileronAngleDegrees = 17.0

AileronEngineFlowGain = 25.0
AileronEngineFreqGain = 1.0
AileronEngineFreqMin = 2.5

AileronVibStallGain = 250.0
AileronVibStalFreq = 25.0

AileronVibRunwayGain = 25.0
AileronVibRunwayFreq = 12.0

# == Ailerons end ==

ForceTrimIntoSim = true
ForcedSimTrim = 0.2

[AP]

# 0 - keep pitch, 1 - keep fpm, 2 - keep alt
PitchMode = 2

ElevatorServoDuMax = 20

# mode 0+ (Pitch)

ElevatorP = 1436.0
ElevatorI = 4.84
ElevatorD = 0.0
ElevatorDuMax = 2552.0

# mode 1+ (Fpm)

PitchP = -0.00001
PitchI = 0.5
PitchD = 0.0
PitchDuMax = 1.0

PitchMaxDeg = 15.0

# mode 2 (Alt)

FpmP = 30.0
FpmI = 20.0
FpmD = 0.0
FpmDuMax = 1000.0
FpmMax = 1000.0

# ap limits

PitchWarningCLForce = 8.0
PitchStartDegradeCLForce = 10000.0
#PitchStartDegradeCLForce = 13.0
PitchMaxCLForce = 18.0

# test
DoStepResponse = false
StepResponseInputFile = "fpm_sr-1.csv"
